version: '3.3'
services:

  frontend:
    image: dimlar/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_vol:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: dimlar/foodgram_backend:latest
    restart: always
    volumes:
      - static_vol:/app/static/
      - media_vol:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_vol:/var/html/static/
      - media_vol:/var/html/media/
    depends_on:
      - backend

volumes:
  db_vol:
  static_vol:
  media_vol:
